# -*- coding: utf-8 -*-
"""band resampling

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eTNqu0s1WAwTOpY9BKuyZjM7xudWB5XV
"""

import ee

# Authenticate and initialize GEE
ee.Authenticate()
ee.Initialize(project='ee-anishamajorproject')

# Define AOI (Replace with actual AOI)
AOI8 = ee.FeatureCollection('projects/ee-anishamajorproject/assets/Tripura_DL')

# Function to mask clouds using the Sentinel-2 QA60 band
def mask_s2_clouds(image):
    qa = image.select('QA60')

    # Bits 10 and 11 are clouds and cirrus, respectively
    cloud_bit_mask = 1 << 10
    cirrus_bit_mask = 1 << 11

    # Mask where clouds & cirrus are NOT present
    mask = qa.bitwiseAnd(cloud_bit_mask).eq(0).And(qa.bitwiseAnd(cirrus_bit_mask).eq(0))

    return image.updateMask(mask)  # Apply mask to remove clouds

# Define start & end dates
start_date = '2023-04-01'
end_date = '2023-04-30'

# Load Sentinel-2 collection, filter by date & AOI
dataset = (
    ee.ImageCollection('COPERNICUS/S2_SR_HARMONIZED')
    .filterBounds(AOI8)
    .filterDate(start_date, end_date)
    .filter(ee.Filter.lt('CLOUDY_PIXEL_PERCENTAGE', 20))
)

# Apply cloud masking
cloud_masked_dataset = dataset.map(mask_s2_clouds)

# Get a sample image to check metadata
sample_image = cloud_masked_dataset.first()

# Get all band names & their resolutions
band_names = sample_image.bandNames().getInfo()
print("Band Resolutions Before Resampling:")
for band in band_names:
    resolution = sample_image.select(band).projection().nominalScale().getInfo()
    print(f"{band} Resolution: {resolution}m")

# Define bands
bands_10m = ['B2', 'B3', 'B4', 'B8']  # Already at 10m
bands_20m = ['B5', 'B6', 'B7', 'B8A', 'B11', 'B12']  # Need resampling

# Function to resample 20m bands to 10m & apply scaling
def process_image(image):
    # Get reference projection from a 10m band (B8)
    reference_proj = image.select('B8').projection()

    # Resample 20m bands to 10m
    resampled_bands = (
        image.select(bands_20m)
        .resample('bilinear')
        .reproject(crs=reference_proj, scale=10)
    )

    # Merge resampled bands with original 10m bands
    merged = image.select(bands_10m).addBands(resampled_bands)

    # Apply scaling AFTER resampling
    scaled = merged.divide(10000)

    return scaled.copyProperties(image, image.propertyNames())

# Apply processing to dataset
processed_dataset = cloud_masked_dataset.map(process_image)

# Create a monthly median composite & clip to AOI
monthly_mosaic = processed_dataset.median().clip(AOI8)

# **Final step: Enforce uniform 10m resolution**
final_mosaic = monthly_mosaic.reproject(
    crs=monthly_mosaic.select('B8').projection(),
    scale=10
)

# Print band resolutions after resampling
print("\nBand Resolutions After Resampling:")
for band in bands_10m + bands_20m:
    resolution = final_mosaic.select(band).projection().nominalScale().getInfo()
    print(f"{band} Resolution After Resampling: {resolution}m")

# Export final image (Example: to Google Drive)
task = ee.batch.Export.image.toDrive(
    image=final_mosaic,
    description="Sentinel2_Resampled_10m",
    folder="GEE_Exports",
    scale=10,
    region=AOI8.geometry(),
    fileFormat="GeoTIFF"
)

# Start export task
task.start()

print("\n✅ Export task started! Check GEE Task Manager.")