# -*- coding: utf-8 -*-
"""LightGBM Forecasting Fire

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-Zt-Got0qrfx3eeanD8hZ2qM9PMhhciP
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import mean_absolute_error, mean_squared_error
from lightgbm import LGBMRegressor
from sklearn.model_selection import train_test_split, GridSearchCV

# --- Step 1: Load and preprocess training data (2012–2023) ---
train_df = pd.read_csv('/content/drive/MyDrive/Prophet Test/As_DimaHasao_Fire_Metrics_2012_2023.csv', parse_dates=['date'])
train_df['date'] = pd.to_datetime(train_df['date'], dayfirst=True)  # Ensure correct date parsing

# --- Step 2: Add time-based features ---
train_df['day_of_year'] = train_df['date'].dt.dayofyear
train_df['month'] = train_df['date'].dt.month
train_df['year'] = train_df['date'].dt.year

# Lag features (e.g. 1-day, 3-day lag)
train_df['lag1'] = train_df['pixel_count'].shift(1)
train_df['lag3'] = train_df['pixel_count'].shift(3)
train_df['rolling7'] = train_df['pixel_count'].rolling(window=7).mean()

# Drop NA rows from lag
train_df.dropna(inplace=True)

# --- Step 3: Prepare Training and Test Data ---
# Split data based on years (training: 2012-2023, testing: 2024)
test_df = pd.read_csv('/content/drive/MyDrive/Prophet Test/As_DimaHasao_Fire_Metrics_2024.csv', parse_dates=['date'])
test_df['date'] = pd.to_datetime(test_df['date'], dayfirst=True)

# Check if there is any data for 2024 in the test set
print(f"Test data 2024: {test_df.shape[0]} rows")

# Filter test data for Mar-May 2024 (March, April, May)
test_data = test_df[test_df['date'].dt.month.isin([3, 4, 5])]

# Check if the filtering resulted in any rows
print(f"Filtered test data for Mar-May 2024: {test_data.shape[0]} rows")

# If no data is available after filtering, raise an error
if test_data.shape[0] == 0:
    raise ValueError("No data available for March-May 2024 in the test set.")

# Add time-based features to test data
test_data['day_of_year'] = test_data['date'].dt.dayofyear
test_data['month'] = test_data['date'].dt.month
test_data['year'] = test_data['date'].dt.year

# Lag features for test data (e.g. 1-day, 3-day lag)
test_data['lag1'] = test_data['pixel_count'].shift(1)
test_data['lag3'] = test_data['pixel_count'].shift(3)
test_data['rolling7'] = test_data['pixel_count'].rolling(window=7).mean()

# Drop NA rows from test data (important for consistency with training data)
test_data.dropna(inplace=True)

# Define features and target for both train and test
X_train = train_df[['day_of_year', 'month', 'lag1', 'lag3', 'rolling7']]
y_train = train_df['pixel_count']

X_test = test_data[['day_of_year', 'month', 'lag1', 'lag3', 'rolling7']]
y_test = test_data['pixel_count']

# --- Step 4: Check for Missing Values in the Test Set ---
# Check if X_test has any missing values
if X_test.isnull().sum().sum() > 0:
    print("Missing values detected in X_test. Dropping rows with NaN values.")
    X_test = X_test.dropna()

# Check for missing values in y_test
if y_test.isnull().sum() > 0:
    print("Missing values detected in y_test. Dropping rows with NaN values.")
    y_test = y_test.dropna()

# --- Step 5: Check Shape of X_test ---
print(f"X_test shape: {X_test.shape}")
if X_test.shape[0] == 0:
    raise ValueError("X_test is empty. Ensure the validation set contains data.")

# --- Step 6: Train the LightGBM Model ---
# Initialize the model
model = LGBMRegressor()

# GridSearchCV to find best hyperparameters
param_grid = {
    'n_estimators': [100, 200],
    'learning_rate': [0.01, 0.1, 0.2],
    'num_leaves': [31, 50],
    'max_depth': [5, 10]
}

grid_search = GridSearchCV(estimator=model, param_grid=param_grid, cv=3, n_jobs=-1)
grid_search.fit(X_train, y_train)

# Get the best model from grid search
final_model = grid_search.best_estimator_

# --- Step 7: Make Predictions ---
y_pred = final_model.predict(X_test)

# --- Step 8: Evaluate the Model ---
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print(f"MAE: {mae:.2f}")
print(f"RMSE: {rmse:.2f}")

# --- Step 9: Plot Actual vs Predicted ---
plt.figure(figsize=(12, 6))
plt.plot(test_data['date'], y_test, label='Actual', marker='o')
plt.plot(test_data['date'], y_pred, label='Predicted', linestyle='--')
plt.title('LightGBM: Actual vs Predicted Pixel Count (2024)')
plt.xlabel('Date')
plt.ylabel('Pixel Count')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import mean_absolute_error, mean_squared_error
from lightgbm import LGBMRegressor
from sklearn.model_selection import train_test_split, GridSearchCV

# --- Step 1: Load and preprocess training data (2012–2023) ---
train_df = pd.read_csv('/content/drive/MyDrive/Prophet Test/As_DimaHasao_Fire_Metrics_2012_2023.csv', parse_dates=['date'])
train_df['date'] = pd.to_datetime(train_df['date'], dayfirst=True)  # Ensure correct date parsing

# --- Step 2: Add time-based features ---
train_df['day_of_year'] = train_df['date'].dt.dayofyear
train_df['month'] = train_df['date'].dt.month
train_df['year'] = train_df['date'].dt.year

# Lag features (e.g. 1-day, 3-day lag)
train_df['lag1'] = train_df['pixel_count'].shift(1)
train_df['lag3'] = train_df['pixel_count'].shift(3)
train_df['rolling7'] = train_df['pixel_count'].rolling(window=7).mean()

# Drop NA rows from lag
train_df.dropna(inplace=True)

# --- Step 3: Prepare Training and Test Data ---
# Split data based on years (training: 2012-2023, testing: 2024)
test_df = pd.read_csv('/content/drive/MyDrive/Prophet Test/As_DimaHasao_Fire_Metrics_2024.csv', parse_dates=['date'])
test_df['date'] = pd.to_datetime(test_df['date'], dayfirst=True)

# Check if there is any data for 2024 in the test set
print(f"Test data 2024: {test_df.shape[0]} rows")

# Filter test data for Mar-May 2024 (March, April, May)
test_data = test_df[test_df['date'].dt.month.isin([3, 4, 5])]

# Check if the filtering resulted in any rows
print(f"Filtered test data for Mar-May 2024: {test_data.shape[0]} rows")

# If no data is available after filtering, raise an error
if test_data.shape[0] == 0:
    raise ValueError("No data available for March-May 2024 in the test set.")

# Add time-based features to test data using .loc[]
test_data.loc[:, 'day_of_year'] = test_data['date'].dt.dayofyear
test_data.loc[:, 'month'] = test_data['date'].dt.month
test_data.loc[:, 'year'] = test_data['date'].dt.year

# Lag features for test data (e.g. 1-day, 3-day lag)
test_data.loc[:, 'lag1'] = test_data['pixel_count'].shift(1)
test_data.loc[:, 'lag3'] = test_data['pixel_count'].shift(3)
test_data.loc[:, 'rolling7'] = test_data['pixel_count'].rolling(window=7).mean()

# Drop NA rows from test data (important for consistency with training data)
test_data.dropna(inplace=True)

# Define features and target for both train and test
X_train = train_df[['day_of_year', 'month', 'lag1', 'lag3', 'rolling7']]
y_train = train_df['pixel_count']

X_test = test_data[['day_of_year', 'month', 'lag1', 'lag3', 'rolling7']]
y_test = test_data['pixel_count']

# --- Step 4: Check for Missing Values in the Test Set ---
# Check if X_test has any missing values
if X_test.isnull().sum().sum() > 0:
    print("Missing values detected in X_test. Dropping rows with NaN values.")
    X_test = X_test.dropna()

# Check for missing values in y_test
if y_test.isnull().sum() > 0:
    print("Missing values detected in y_test. Dropping rows with NaN values.")
    y_test = y_test.dropna()

# --- Step 5: Check Shape of X_test ---
print(f"X_test shape: {X_test.shape}")
if X_test.shape[0] == 0:
    raise ValueError("X_test is empty. Ensure the validation set contains data.")

# --- Step 6: Train the LightGBM Model ---
# Initialize the model
model = LGBMRegressor()

# GridSearchCV to find best hyperparameters
param_grid = {
    'n_estimators': [100, 200],
    'learning_rate': [0.01, 0.1, 0.2],
    'num_leaves': [31, 50],
    'max_depth': [5, 10]
}

grid_search = GridSearchCV(estimator=model, param_grid=param_grid, cv=3, n_jobs=-1)
grid_search.fit(X_train, y_train)

# Get the best model from grid search
final_model = grid_search.best_estimator_

# --- Step 7: Make Predictions ---
y_pred = final_model.predict(X_test)

# --- Step 8: Evaluate the Model ---
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print(f"MAE: {mae:.2f}")
print(f"RMSE: {rmse:.2f}")

# --- Step 9: Plot Actual vs Predicted ---
plt.figure(figsize=(12, 6))
plt.plot(test_data['date'], y_test, label='Actual', marker='o')
plt.plot(test_data['date'], y_pred, label='Predicted', linestyle='--')
plt.title('LightGBM: Actual vs Predicted Pixel Count (2024)')
plt.xlabel('Date')
plt.ylabel('Pixel Count')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from lightgbm import LGBMRegressor
from sklearn.model_selection import train_test_split, GridSearchCV

# --- Step 1: Load and preprocess training data (2012–2023) ---
train_df = pd.read_csv('/content/drive/MyDrive/Prophet Test/As_DimaHasao_Fire_Metrics_2012_2023.csv', parse_dates=['date'])
train_df['date'] = pd.to_datetime(train_df['date'], dayfirst=True)  # Ensure correct date parsing

# Feature engineering: Create lag features and rolling window features
train_df['day_of_year'] = train_df['date'].dt.dayofyear
train_df['month'] = train_df['date'].dt.month
train_df['year'] = train_df['date'].dt.year

train_df['lag1'] = train_df['pixel_count'].shift(1)
train_df['lag3'] = train_df['pixel_count'].shift(3)
train_df['lag7'] = train_df['pixel_count'].shift(7)
train_df['rolling7'] = train_df['pixel_count'].rolling(window=7).mean()

# Drop NA rows from lag features and rolling window features
train_df.dropna(inplace=True)

# --- Step 2: Load 2024 validation data ---
val_df = pd.read_csv('/content/drive/MyDrive/Prophet Test/As_DimaHasao_Fire_Metrics_2024.csv', parse_dates=['date'])
val_df['date'] = pd.to_datetime(val_df['date'], dayfirst=True)  # Ensure correct date parsing
val_df = val_df[['date', 'pixel_count']]

# Filter for Mar-May 2024
val_df = val_df[val_df['date'].dt.month.isin([3, 4, 5])]

# Feature engineering on the validation set (same as the training set)
val_df['day_of_year'] = val_df['date'].dt.dayofyear
val_df['month'] = val_df['date'].dt.month
val_df['year'] = val_df['date'].dt.year

val_df['lag1'] = val_df['pixel_count'].shift(1)
val_df['lag3'] = val_df['pixel_count'].shift(3)
val_df['lag7'] = val_df['pixel_count'].shift(7)
val_df['rolling7'] = val_df['pixel_count'].rolling(window=7).mean()

# Drop NA rows from lag features and rolling window features
val_df.dropna(inplace=True)

# --- Step 3: Train-test split for validation ---
X_train = train_df[['day_of_year', 'month', 'lag1', 'lag3', 'lag7', 'rolling7']]
y_train = train_df['pixel_count']
X_test = val_df[['day_of_year', 'month', 'lag1', 'lag3', 'lag7', 'rolling7']]
y_test = val_df['pixel_count']

# --- Step 4: Hyperparameter tuning with GridSearchCV ---
param_grid = {
    'num_leaves': [31, 50, 100],  # Increase number of leaves
    'max_depth': [10, 20, 30],  # Increase max depth
    'learning_rate': [0.01, 0.05, 0.1],  # Learning rate
    'n_estimators': [100, 200, 500],  # More trees for better performance
    'min_data_in_leaf': [20, 50, 100],  # Control the minimum data in each leaf
    'boosting_type': ['gbdt', 'dart', 'goss']  # Different boosting types to try
}

grid_search = GridSearchCV(estimator=LGBMRegressor(), param_grid=param_grid, cv=3, n_jobs=-1)
grid_search.fit(X_train, y_train)

# Best parameters found
print(f"Best parameters found: {grid_search.best_params_}")

# Use the best model found
final_model = grid_search.best_estimator_

# --- Step 5: Make Predictions and Evaluate the Model ---
y_pred = final_model.predict(X_test)

mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"MAE: {mae:.2f}")
print(f"MSE: {mse:.2f}")
print(f"RMSE: {rmse:.2f}")
print(f"R²: {r2:.4f}")

# --- Step 6: Plot Actual vs Predicted ---
plt.figure(figsize=(12, 6))
plt.plot(val_df['date'], y_test, label='Actual', marker='o')
plt.plot(val_df['date'], y_pred, label='Predicted', linestyle='--')
plt.title('LightGBM: Actual vs Predicted Pixel Count (Mar–May 2024)')
plt.xlabel('Date')
plt.ylabel('Pixel Count')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

"""**2012 to 2023 - predict for 2024, 2012 to 2024, predict for 2025**"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from lightgbm import LGBMRegressor
from sklearn.model_selection import GridSearchCV

# --- Step 1: Load and preprocess full data (2012–2024) ---
full_df = pd.read_csv('/content/drive/MyDrive/Forest Only - Fire, LST, and CH4/Tripura_ForestOnly_FireMetrics_2012_2024.csv', parse_dates=['date'])
full_df['date'] = pd.to_datetime(full_df['date'], dayfirst=True)

# Feature engineering
full_df['day_of_year'] = full_df['date'].dt.dayofyear
full_df['month'] = full_df['date'].dt.month
full_df['year'] = full_df['date'].dt.year

full_df['lag1'] = full_df['pixel_count'].shift(1)
full_df['lag3'] = full_df['pixel_count'].shift(3)
full_df['lag7'] = full_df['pixel_count'].shift(7)
full_df['rolling7'] = full_df['pixel_count'].rolling(window=7).mean()

# Drop NA rows from lag/rolling
full_df.dropna(inplace=True)

# --- Step 2: Predict and validate for 2024 ---
train_2024 = full_df[full_df['year'] < 2024]
valid_2024 = full_df[full_df['year'] == 2024]
valid_2024 = valid_2024[valid_2024['month'].isin([3, 4, 5])]  # Mar–May only

X_train_2024 = train_2024[['day_of_year', 'month', 'lag1', 'lag3', 'lag7', 'rolling7']]
y_train_2024 = train_2024['pixel_count']
X_valid_2024 = valid_2024[['day_of_year', 'month', 'lag1', 'lag3', 'lag7', 'rolling7']]
y_valid_2024 = valid_2024['pixel_count']

# Grid Search
param_grid = {
    'num_leaves': [31, 50],
    'max_depth': [10, 20],
    'learning_rate': [0.01, 0.05],
    'n_estimators': [100, 200],
    'min_data_in_leaf': [20, 50],
    'boosting_type': ['gbdt', 'dart']
}
grid_search_2024 = GridSearchCV(estimator=LGBMRegressor(), param_grid=param_grid, cv=3, n_jobs=-1)
grid_search_2024.fit(X_train_2024, y_train_2024)
final_model_2024 = grid_search_2024.best_estimator_

# Predict 2024
y_pred_2024 = final_model_2024.predict(X_valid_2024)

print("\n🔎 2024 Validation Results:")
print(f"MAE: {mean_absolute_error(y_valid_2024, y_pred_2024):.2f}")
print(f"MSE: {mean_squared_error(y_valid_2024, y_pred_2024):.2f}")
print(f"RMSE: {np.sqrt(mean_squared_error(y_valid_2024, y_pred_2024)):.2f}")
print(f"R²: {r2_score(y_valid_2024, y_pred_2024):.4f}")

# Plot 2024 results
plt.figure(figsize=(12, 6))
plt.plot(valid_2024['date'], y_valid_2024, label='Actual', marker='o')
plt.plot(valid_2024['date'], y_pred_2024, label='Predicted', linestyle='--')
plt.title('LightGBM: Actual vs Predicted Pixel Count (Mar–May 2024)')
plt.xlabel('Date')
plt.ylabel('Pixel Count')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

# --- Step 3: Load and preprocess 2025 data ---
df_2025 = pd.read_csv('/content/drive/MyDrive/Forest Only - Fire, LST, and CH4/Tripura_ForestOnly_FireMetrics_2025.csv', parse_dates=['date'])
df_2025['date'] = pd.to_datetime(df_2025['date'], dayfirst=True)

# Feature engineering for 2025
df_2025['day_of_year'] = df_2025['date'].dt.dayofyear
df_2025['month'] = df_2025['date'].dt.month
df_2025['year'] = df_2025['date'].dt.year

# Now it's safe to filter Mar–May
df_2025 = df_2025[df_2025['month'].isin([3, 4, 5])]

# Lag/rolling features
df_2025['lag1'] = df_2025['pixel_count'].shift(1)
df_2025['lag3'] = df_2025['pixel_count'].shift(3)
df_2025['lag7'] = df_2025['pixel_count'].shift(7)
df_2025['rolling7'] = df_2025['pixel_count'].rolling(window=7).mean()
df_2025.dropna(inplace=True)

# --- Step 4: Train on 2012–2024 and predict for 2025 ---
train_2025 = full_df.copy()  # Includes 2012–2024
X_train_2025 = train_2025[['day_of_year', 'month', 'lag1', 'lag3', 'lag7', 'rolling7']]
y_train_2025 = train_2025['pixel_count']
X_valid_2025 = df_2025[['day_of_year', 'month', 'lag1', 'lag3', 'lag7', 'rolling7']]
y_valid_2025 = df_2025['pixel_count']

# Train model (reuse grid from above, or retrain)
final_model_2025 = LGBMRegressor(**grid_search_2024.best_params_)
final_model_2025.fit(X_train_2025, y_train_2025)

# Predict 2025
y_pred_2025 = final_model_2025.predict(X_valid_2025)

print("\n🔎 2025 Validation Results:")
print(f"MAE: {mean_absolute_error(y_valid_2025, y_pred_2025):.2f}")
print(f"MSE: {mean_squared_error(y_valid_2025, y_pred_2025):.2f}")
print(f"RMSE: {np.sqrt(mean_squared_error(y_valid_2025, y_pred_2025)):.2f}")
print(f"R²: {r2_score(y_valid_2025, y_pred_2025):.4f}")

# Plot 2025 results
plt.figure(figsize=(12, 6))
plt.plot(df_2025['date'], y_valid_2025, label='Actual', marker='o')
plt.plot(df_2025['date'], y_pred_2025, label='Predicted', linestyle='--')
plt.title('Tripura - LightGBM: Actual vs Predicted Pixel Count (Mar–May 2025)')
plt.xlabel('Date')
plt.ylabel('Pixel Count')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

# Export 2025 predictions to CSV
df_2025_export = df_2025.copy()
df_2025_export['predicted_pixel_count'] = y_pred_2025
df_2025_export.to_csv('/content/drive/MyDrive/Predicted csvs/Tripura_ForestOnlyFire_LightGBM_Prediction_2025.csv', index=False)