# -*- coding: utf-8 -*-
"""LightGBM Forecasting Fire

Automatically generated by Colab.

"""**2012 to 2023 - predict for 2024, 2012 to 2024, predict for 2025**"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from lightgbm import LGBMRegressor
from sklearn.model_selection import GridSearchCV

# --- Step 1: Load and preprocess full data (2012–2024) ---
full_df = pd.read_csv('/content/drive/MyDrive/Forest Only - Fire, LST, and CH4/Tripura_ForestOnly_FireMetrics_2012_2024.csv', parse_dates=['date'])
full_df['date'] = pd.to_datetime(full_df['date'], dayfirst=True)

# Feature engineering
full_df['day_of_year'] = full_df['date'].dt.dayofyear
full_df['month'] = full_df['date'].dt.month
full_df['year'] = full_df['date'].dt.year

full_df['lag1'] = full_df['pixel_count'].shift(1)
full_df['lag3'] = full_df['pixel_count'].shift(3)
full_df['lag7'] = full_df['pixel_count'].shift(7)
full_df['rolling7'] = full_df['pixel_count'].rolling(window=7).mean()

# Drop NA rows from lag/rolling
full_df.dropna(inplace=True)

# --- Step 2: Predict and validate for 2024 ---
train_2024 = full_df[full_df['year'] < 2024]
valid_2024 = full_df[full_df['year'] == 2024]
valid_2024 = valid_2024[valid_2024['month'].isin([3, 4, 5])]  # Mar–May only

X_train_2024 = train_2024[['day_of_year', 'month', 'lag1', 'lag3', 'lag7', 'rolling7']]
y_train_2024 = train_2024['pixel_count']
X_valid_2024 = valid_2024[['day_of_year', 'month', 'lag1', 'lag3', 'lag7', 'rolling7']]
y_valid_2024 = valid_2024['pixel_count']

# Grid Search
param_grid = {
    'num_leaves': [31, 50],
    'max_depth': [10, 20],
    'learning_rate': [0.01, 0.05],
    'n_estimators': [100, 200],
    'min_data_in_leaf': [20, 50],
    'boosting_type': ['gbdt', 'dart']
}
grid_search_2024 = GridSearchCV(estimator=LGBMRegressor(), param_grid=param_grid, cv=3, n_jobs=-1)
grid_search_2024.fit(X_train_2024, y_train_2024)
final_model_2024 = grid_search_2024.best_estimator_

# Predict 2024
y_pred_2024 = final_model_2024.predict(X_valid_2024)

print("\n🔎 2024 Validation Results:")
print(f"MAE: {mean_absolute_error(y_valid_2024, y_pred_2024):.2f}")
print(f"MSE: {mean_squared_error(y_valid_2024, y_pred_2024):.2f}")
print(f"RMSE: {np.sqrt(mean_squared_error(y_valid_2024, y_pred_2024)):.2f}")
print(f"R²: {r2_score(y_valid_2024, y_pred_2024):.4f}")

# Plot 2024 results
plt.figure(figsize=(12, 6))
plt.plot(valid_2024['date'], y_valid_2024, label='Actual', marker='o')
plt.plot(valid_2024['date'], y_pred_2024, label='Predicted', linestyle='--')
plt.title('LightGBM: Actual vs Predicted Pixel Count (Mar–May 2024)')
plt.xlabel('Date')
plt.ylabel('Pixel Count')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

# --- Step 3: Load and preprocess 2025 data ---
df_2025 = pd.read_csv('/content/drive/MyDrive/Forest Only - Fire, LST, and CH4/Tripura_ForestOnly_FireMetrics_2025.csv', parse_dates=['date'])
df_2025['date'] = pd.to_datetime(df_2025['date'], dayfirst=True)

# Feature engineering for 2025
df_2025['day_of_year'] = df_2025['date'].dt.dayofyear
df_2025['month'] = df_2025['date'].dt.month
df_2025['year'] = df_2025['date'].dt.year

# Now it's safe to filter Mar–May
df_2025 = df_2025[df_2025['month'].isin([3, 4, 5])]

# Lag/rolling features
df_2025['lag1'] = df_2025['pixel_count'].shift(1)
df_2025['lag3'] = df_2025['pixel_count'].shift(3)
df_2025['lag7'] = df_2025['pixel_count'].shift(7)
df_2025['rolling7'] = df_2025['pixel_count'].rolling(window=7).mean()
df_2025.dropna(inplace=True)

# --- Step 4: Train on 2012–2024 and predict for 2025 ---
train_2025 = full_df.copy()  # Includes 2012–2024
X_train_2025 = train_2025[['day_of_year', 'month', 'lag1', 'lag3', 'lag7', 'rolling7']]
y_train_2025 = train_2025['pixel_count']
X_valid_2025 = df_2025[['day_of_year', 'month', 'lag1', 'lag3', 'lag7', 'rolling7']]
y_valid_2025 = df_2025['pixel_count']

# Train model (reuse grid from above, or retrain)
final_model_2025 = LGBMRegressor(**grid_search_2024.best_params_)
final_model_2025.fit(X_train_2025, y_train_2025)

# Predict 2025
y_pred_2025 = final_model_2025.predict(X_valid_2025)

print("\n🔎 2025 Validation Results:")
print(f"MAE: {mean_absolute_error(y_valid_2025, y_pred_2025):.2f}")
print(f"MSE: {mean_squared_error(y_valid_2025, y_pred_2025):.2f}")
print(f"RMSE: {np.sqrt(mean_squared_error(y_valid_2025, y_pred_2025)):.2f}")
print(f"R²: {r2_score(y_valid_2025, y_pred_2025):.4f}")

# Plot 2025 results
plt.figure(figsize=(12, 6))
plt.plot(df_2025['date'], y_valid_2025, label='Actual', marker='o')
plt.plot(df_2025['date'], y_pred_2025, label='Predicted', linestyle='--')
plt.title('Tripura - LightGBM: Actual vs Predicted Pixel Count (Mar–May 2025)')
plt.xlabel('Date')
plt.ylabel('Pixel Count')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

# Export 2025 predictions to CSV
df_2025_export = df_2025.copy()
df_2025_export['predicted_pixel_count'] = y_pred_2025
df_2025_export.to_csv('/content/drive/MyDrive/Predicted csvs/Tripura_ForestOnlyFire_LightGBM_Prediction_2025.csv', index=False)
