# -*- coding: utf-8 -*-
"""XGBoost Forecasting Fire

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FZ1U5XLCRhYiyQwn_NEet2C-pFEbm91F
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import mean_absolute_error, mean_squared_error
from xgboost import XGBRegressor

# --- Step 1: Load and preprocess full data (2012–2024) ---
train_df = pd.read_csv('/content/drive/MyDrive/Prophet Test/As_DimaHasao_Fire_Metrics_2012_2023.csv', parse_dates=['date'])
val_df = pd.read_csv('/content/drive/MyDrive/Prophet Test/As_DimaHasao_Fire_Metrics_2024.csv', parse_dates=['date'])

# Combine and preprocess
full_df = pd.concat([train_df, val_df], ignore_index=True)
full_df['date'] = pd.to_datetime(full_df['date'], dayfirst=True)
full_df['year'] = full_df['date'].dt.year
full_df['month'] = full_df['date'].dt.month
full_df['day_of_year'] = full_df['date'].dt.dayofyear

# Keep only March–May data
full_df = full_df[full_df['month'].isin([3, 4, 5])]

# Sort by date to maintain temporal order
full_df.sort_values('date', inplace=True)

# --- Step 2: Create lag and rolling features ---
full_df['lag1'] = full_df['pixel_count'].shift(1)
full_df['lag3'] = full_df['pixel_count'].shift(3)
full_df['rolling7'] = full_df['pixel_count'].rolling(window=7).mean()

# Drop NA rows from lag/rolling
full_df.dropna(inplace=True)

# --- Step 3: Train-test split ---
train_df = full_df[full_df['year'] < 2024]
test_df = full_df[full_df['year'] == 2024]

X_train = train_df[['day_of_year', 'month', 'lag1', 'lag3', 'rolling7']]
y_train = train_df['pixel_count']
X_test = test_df[['day_of_year', 'month', 'lag1', 'lag3', 'rolling7']]
y_test = test_df['pixel_count']

# --- Step 4: Train XGBoost model ---
model = XGBRegressor(n_estimators=100, learning_rate=0.1, random_state=42)
model.fit(X_train, y_train)

# --- Step 5: Predict and evaluate ---
y_pred = model.predict(X_test)

mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
print(f"MAE: {mae:.2f}")
print(f"RMSE: {rmse:.2f}")

# --- Step 6: Plot actual vs predicted ---
plt.figure(figsize=(12, 6))
plt.plot(test_df['date'], y_test.values, label='Actual', marker='o')
plt.plot(test_df['date'], y_pred, label='Predicted', linestyle='--')
plt.title('XGBoost: Actual vs Predicted Pixel Count (Mar–May 2024)')
plt.xlabel('Date')
plt.ylabel('Pixel Count')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from xgboost import XGBRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error

# --- Load and preprocess training data (2012–2023) ---
train_df = pd.read_csv('/content/drive/MyDrive/Prophet Test/As_DimaHasao_Fire_Metrics_2012_2023.csv', parse_dates=['date'])
train_df['date'] = pd.to_datetime(train_df['date'], dayfirst=True)

# --- Load validation data (2024) ---
val_df = pd.read_csv('/content/drive/MyDrive/Prophet Test/As_DimaHasao_Fire_Metrics_2024.csv', parse_dates=['date'])
val_df['date'] = pd.to_datetime(val_df['date'], dayfirst=True)

# --- Combine and mark year ---
train_df['year'] = train_df['date'].dt.year
val_df['year'] = val_df['date'].dt.year
df = pd.concat([train_df, val_df], ignore_index=True)

# --- Filter to fire season only (optional) ---
df = df[df['date'].dt.month.isin([3, 4, 5])]

# --- Feature engineering ---
df['day_of_year'] = df['date'].dt.dayofyear
df['month'] = df['date'].dt.month
df['weekofyear'] = df['date'].dt.isocalendar().week.astype(int)
df['weekday'] = df['date'].dt.weekday
df['is_april'] = (df['date'].dt.month == 4).astype(int)
df['is_april_first_week'] = ((df['date'].dt.month == 4) & (df['date'].dt.day <= 6)).astype(int)

# Lag & rolling features
df['lag1'] = df['pixel_count'].shift(1)
df['lag2'] = df['pixel_count'].shift(2)
df['lag3'] = df['pixel_count'].shift(3)
df['lag5'] = df['pixel_count'].shift(5)
df['lag7'] = df['pixel_count'].shift(7)

df['rolling3'] = df['pixel_count'].rolling(3).mean()
df['rolling7'] = df['pixel_count'].rolling(7).mean()
df['rolling14'] = df['pixel_count'].rolling(14).mean()
df['rolling_std7'] = df['pixel_count'].rolling(7).std()
df['target_smooth'] = df['pixel_count'].ewm(span=7).mean()

# Drop rows with NA from lags/rolls
df.dropna(inplace=True)

# --- Train/test split ---
train_df = df[df['year'] < 2024]
test_df = df[df['year'] == 2024]

features = [
    'day_of_year', 'month', 'weekofyear', 'weekday',
    'is_april', 'is_april_first_week',
    'lag1', 'lag2', 'lag3', 'lag5', 'lag7',
    'rolling3', 'rolling7', 'rolling14', 'rolling_std7',
    'target_smooth'
]

X_train = train_df[features]
y_train = train_df['pixel_count']
X_test = test_df[features]
y_test = test_df['pixel_count']

# --- XGBoost model with tuned parameters ---
model = XGBRegressor(
    n_estimators=300,
    max_depth=4,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    gamma=0.2,
    random_state=42
)

model.fit(X_train, y_train)

# --- Predict and evaluate ---
y_pred = model.predict(X_test)
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print(f"MAE: {mae:.2f}")
print(f"RMSE: {rmse:.2f}")

# --- Plot results ---
plt.figure(figsize=(12, 6))
plt.plot(test_df['date'], y_test, label='Actual', marker='o')
plt.plot(test_df['date'], y_pred, label='Predicted', linestyle='--')
plt.title('XGBoost: Actual vs Predicted Pixel Count (Mar–May 2024)')
plt.xlabel('Date')
plt.ylabel('Pixel Count')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

"""With GridSearchCV"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from xgboost import XGBRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error

# --- Load and preprocess training data (2012–2023) ---
train_df = pd.read_csv('/content/drive/MyDrive/Prophet Test/As_DimaHasao_Fire_Metrics_2012_2023.csv', parse_dates=['date'])
train_df['date'] = pd.to_datetime(train_df['date'], dayfirst=True)

# --- Load validation data (2024) ---
val_df = pd.read_csv('/content/drive/MyDrive/Prophet Test/As_DimaHasao_Fire_Metrics_2024.csv', parse_dates=['date'])
val_df['date'] = pd.to_datetime(val_df['date'], dayfirst=True)

# --- Combine and mark year ---
train_df['year'] = train_df['date'].dt.year
val_df['year'] = val_df['date'].dt.year
df = pd.concat([train_df, val_df], ignore_index=True)

# --- Filter to fire season only (optional) ---
df = df[df['date'].dt.month.isin([3, 4, 5])]

# --- Feature engineering ---
df['day_of_year'] = df['date'].dt.dayofyear
df['month'] = df['date'].dt.month
df['weekofyear'] = df['date'].dt.isocalendar().week.astype(int)
df['weekday'] = df['date'].dt.weekday
df['is_april'] = (df['date'].dt.month == 4).astype(int)
df['is_april_first_week'] = ((df['date'].dt.month == 4) & (df['date'].dt.day <= 6)).astype(int)

# Lag & rolling features
df['lag1'] = df['pixel_count'].shift(1)
df['lag2'] = df['pixel_count'].shift(2)
df['lag3'] = df['pixel_count'].shift(3)
df['lag5'] = df['pixel_count'].shift(5)
df['lag7'] = df['pixel_count'].shift(7)

df['rolling3'] = df['pixel_count'].rolling(3).mean()
df['rolling7'] = df['pixel_count'].rolling(7).mean()
df['rolling14'] = df['pixel_count'].rolling(14).mean()
df['rolling_std7'] = df['pixel_count'].rolling(7).std()
df['target_smooth'] = df['pixel_count'].ewm(span=7).mean()

# Drop rows with NA from lags/rolls
df.dropna(inplace=True)

# --- Train/test split ---
train_df = df[df['year'] < 2024]
test_df = df[df['year'] == 2024]

features = [
    'day_of_year', 'month', 'weekofyear', 'weekday',
    'is_april', 'is_april_first_week',
    'lag1', 'lag2', 'lag3', 'lag5', 'lag7',
    'rolling3', 'rolling7', 'rolling14', 'rolling_std7',
    'target_smooth'
]

X_train = train_df[features]
y_train = train_df['pixel_count']
X_test = test_df[features]
y_test = test_df['pixel_count']

# --- XGBoost model with tuned parameters ---
model = XGBRegressor(
    n_estimators=300,
    max_depth=4,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    gamma=0.2,
    random_state=42
)

model.fit(X_train, y_train)

# --- Predict and evaluate ---
y_pred = model.predict(X_test)
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print(f"MAE: {mae:.2f}")
print(f"RMSE: {rmse:.2f}")

# --- Plot results ---
plt.figure(figsize=(12, 6))
plt.plot(test_df['date'], y_test, label='Actual', marker='o')
plt.plot(test_df['date'], y_pred, label='Predicted', linestyle='--')
plt.title('XGBoost: Actual vs Predicted Pixel Count (Mar–May 2024)')
plt.xlabel('Date')
plt.ylabel('Pixel Count')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

from sklearn.model_selection import GridSearchCV
from xgboost import XGBRegressor

param_grid = {
    'n_estimators': [100, 200, 300],
    'max_depth': [3, 4, 5],
    'learning_rate': [0.01, 0.05, 0.1],
    'subsample': [0.7, 0.8, 1.0],
    'colsample_bytree': [0.7, 0.8, 1.0],
    'gamma': [0, 0.1, 0.2]
}

xgb = XGBRegressor(random_state=42)
grid_search = GridSearchCV(
    estimator=xgb,
    param_grid=param_grid,
    scoring='neg_mean_absolute_error',
    cv=3,
    verbose=1,
    n_jobs=-1
)

grid_search.fit(X_train, y_train)
print("Best parameters:", grid_search.best_params_)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from xgboost import XGBRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# --- Load and preprocess training data (2012–2023) ---
train_df = pd.read_csv('/content/drive/MyDrive/Prophet Test/As_DimaHasao_Fire_Metrics_2012_2023.csv', parse_dates=['date'])
train_df['date'] = pd.to_datetime(train_df['date'], dayfirst=True)

# --- Load validation data (2024) ---
val_df = pd.read_csv('/content/drive/MyDrive/Prophet Test/As_DimaHasao_Fire_Metrics_2024.csv', parse_dates=['date'])
val_df['date'] = pd.to_datetime(val_df['date'], dayfirst=True)

# --- Combine and mark year ---
train_df['year'] = train_df['date'].dt.year
val_df['year'] = val_df['date'].dt.year
df = pd.concat([train_df, val_df], ignore_index=True)

# --- Filter to fire season only (optional) ---
df = df[df['date'].dt.month.isin([3, 4, 5])]

# --- Feature engineering ---
df['day_of_year'] = df['date'].dt.dayofyear
df['month'] = df['date'].dt.month
df['weekofyear'] = df['date'].dt.isocalendar().week.astype(int)
df['weekday'] = df['date'].dt.weekday
df['is_april'] = (df['date'].dt.month == 4).astype(int)
df['is_april_first_week'] = ((df['date'].dt.month == 4) & (df['date'].dt.day <= 6)).astype(int)

# Lag & rolling features
df['lag1'] = df['pixel_count'].shift(1)
df['lag2'] = df['pixel_count'].shift(2)
df['lag3'] = df['pixel_count'].shift(3)
df['lag5'] = df['pixel_count'].shift(5)
df['lag7'] = df['pixel_count'].shift(7)

df['rolling3'] = df['pixel_count'].rolling(3).mean()
df['rolling7'] = df['pixel_count'].rolling(7).mean()
df['rolling14'] = df['pixel_count'].rolling(14).mean()
df['rolling_std7'] = df['pixel_count'].rolling(7).std()
df['target_smooth'] = df['pixel_count'].ewm(span=7).mean()

# Drop rows with NA from lags/rolls
df.dropna(inplace=True)

# --- Train/test split ---
train_df = df[df['year'] < 2024]
test_df = df[df['year'] == 2024]

features = [
    'day_of_year', 'month', 'weekofyear', 'weekday',
    'is_april', 'is_april_first_week',
    'lag1', 'lag2', 'lag3', 'lag5', 'lag7',
    'rolling3', 'rolling7', 'rolling14', 'rolling_std7',
    'target_smooth'
]

X_train = train_df[features]
y_train = train_df['pixel_count']
X_test = test_df[features]
y_test = test_df['pixel_count']

# --- XGBoost model with tuned parameters ---
model = XGBRegressor(
    n_estimators=300,
    max_depth=3,
    learning_rate=0.1,
    subsample=0.7,
    colsample_bytree=0.8,
    gamma=0.2,
    random_state=42
)

model.fit(X_train, y_train)

# --- Predict and evaluate ---
y_pred = model.predict(X_test)
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"MAE: {mae:.2f}")
print(f"MSE: {mse:.2f}")
print(f"RMSE: {rmse:.2f}")
print(f"R²: {r2:.4f}")

# --- Plot results ---
plt.figure(figsize=(12, 6))
plt.plot(test_df['date'], y_test, label='Actual', marker='o')
plt.plot(test_df['date'], y_pred, label='Predicted', linestyle='--')
plt.title('XGBoost: Actual vs Predicted Pixel Count (Mar–May 2024)')
plt.xlabel('Date')
plt.ylabel('Pixel Count')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

"""**2012 to 2023 - predict for 2024, 2012 to 2024, predict for 2025**"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from xgboost import XGBRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# --- Load full data (2012–2024) ---
df_all = pd.read_csv('/content/drive/MyDrive/Forest Only - Fire, LST, and CH4/Tripura_ForestOnly_FireMetrics_2012_2024.csv', parse_dates=['date'])
df_all['date'] = pd.to_datetime(df_all['date'], dayfirst=True)

# --- Load 2025 actuals ---
df_2025 = pd.read_csv('/content/drive/MyDrive/Forest Only - Fire, LST, and CH4/Tripura_ForestOnly_FireMetrics_2025.csv', parse_dates=['date'])
df_2025['date'] = pd.to_datetime(df_2025['date'], dayfirst=True)
df_2025 = df_2025[['date', 'pixel_count']]

# --- Feature Engineering ---
def add_lag_features(df):
    df = df.copy()
    df['day_of_year'] = df['date'].dt.dayofyear
    df['month'] = df['date'].dt.month
    df['weekofyear'] = df['date'].dt.isocalendar().week.astype(int)
    df['weekday'] = df['date'].dt.weekday
    df['is_april'] = (df['date'].dt.month == 4).astype(int)
    df['is_april_first_week'] = ((df['date'].dt.month == 4) & (df['date'].dt.day <= 6)).astype(int)
    df['lag1'] = df['pixel_count'].shift(1)
    df['lag2'] = df['pixel_count'].shift(2)
    df['lag3'] = df['pixel_count'].shift(3)
    df['lag5'] = df['pixel_count'].shift(5)
    df['lag7'] = df['pixel_count'].shift(7)
    df['rolling3'] = df['pixel_count'].rolling(3).mean()
    df['rolling7'] = df['pixel_count'].rolling(7).mean()
    df['rolling14'] = df['pixel_count'].rolling(14).mean()
    df['rolling_std7'] = df['pixel_count'].rolling(7).std()
    df['target_smooth'] = df['pixel_count'].ewm(span=7).mean()
    return df.dropna()

# --- Preprocess full historical data ---
df_all['year'] = df_all['date'].dt.year
df_all = df_all[df_all['date'].dt.month.isin([3, 4, 5])]
df_all = add_lag_features(df_all)

# --- Train-validation split for 2024 ---
df_train_2024 = df_all[df_all['year'] < 2024]
df_valid_2024 = df_all[df_all['year'] == 2024]

features = [
    'day_of_year', 'month', 'weekofyear', 'weekday',
    'is_april', 'is_april_first_week',
    'lag1', 'lag2', 'lag3', 'lag5', 'lag7',
    'rolling3', 'rolling7', 'rolling14', 'rolling_std7',
    'target_smooth'
]

X_train_2024 = df_train_2024[features]
y_train_2024 = df_train_2024['pixel_count']
X_valid_2024 = df_valid_2024[features]
y_valid_2024 = df_valid_2024['pixel_count']

# --- Train model on 2012–2023, validate on 2024 ---
model = XGBRegressor(
    n_estimators=300,
    max_depth=3,
    learning_rate=0.1,
    subsample=0.7,
    colsample_bytree=0.8,
    gamma=0.2,
    random_state=42
)
model.fit(X_train_2024, y_train_2024)
y_pred_2024 = model.predict(X_valid_2024)

print("🔎 2024 Validation Results:")
print(f"MAE: {mean_absolute_error(y_valid_2024, y_pred_2024):.2f}")
print(f"MSE: {mean_squared_error(y_valid_2024, y_pred_2024):.2f}")
print(f"RMSE: {np.sqrt(mean_squared_error(y_valid_2024, y_pred_2024)):.2f}")
print(f"R²: {r2_score(y_valid_2024, y_pred_2024):.4f}")

plt.figure(figsize=(12, 6))
plt.plot(df_valid_2024['date'], y_valid_2024, label='Actual 2024', marker='o')
plt.plot(df_valid_2024['date'], y_pred_2024, label='Predicted 2024', linestyle='--')
plt.title('XGBoost: Actual vs Predicted Pixel Count (Mar–May 2024)')
plt.xlabel('Date')
plt.ylabel('Pixel Count')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

# === Predict 2025 ===
# Add historical data before 2025 to provide lag context
history_for_2025 = df_all[df_all['date'] < '2025-01-01'].copy()
df_2025['year'] = df_2025['date'].dt.year
df_2025 = df_2025[df_2025['date'].dt.month.isin([3, 4, 5])]
df_full_for_2025 = pd.concat([history_for_2025[['date', 'pixel_count']], df_2025], ignore_index=True)
df_full_for_2025 = add_lag_features(df_full_for_2025)
df_2025_ready = df_full_for_2025[df_full_for_2025['date'].dt.year == 2025]

X_train_2025 = df_all[features]
y_train_2025 = df_all['pixel_count']
X_2025 = df_2025_ready[features]
y_2025 = df_2025_ready['pixel_count']

# Retrain on all past years and predict 2025
model.fit(X_train_2025, y_train_2025)
y_pred_2025 = model.predict(X_2025)

# --- Evaluation for 2025 ---
print("\n🔎 2025 Validation Results:")
print(f"MAE: {mean_absolute_error(y_2025, y_pred_2025):.2f}")
print(f"MSE: {mean_squared_error(y_2025, y_pred_2025):.2f}")
print(f"RMSE: {np.sqrt(mean_squared_error(y_2025, y_pred_2025)):.2f}")
print(f"R²: {r2_score(y_2025, y_pred_2025):.4f}")

# --- Plot 2025 ---
plt.figure(figsize=(12, 6))
plt.plot(df_2025_ready['date'], y_2025, label='Actual 2025', marker='o')
plt.plot(df_2025_ready['date'], y_pred_2025, label='Predicted 2025', linestyle='--')
plt.title('Tripura - XGBoost: Actual vs Predicted Pixel Count (Mar–May 2025)')
plt.xlabel('Date')
plt.ylabel('Pixel Count')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

# --- Export predictions ---
df_export_2025 = pd.DataFrame({
    'ds': df_2025_ready['date'],
    'actual': y_2025,
    'predicted': y_pred_2025
})
df_export_2025.to_csv('/content/drive/MyDrive/Predicted csvs/Tripura_ForestOnlyFire_XGBoost_Prediction_2025.csv', index=False)
print("✅ Exported 2025 predicted values to: Tripura_ForestOnlyFire_XGBoost_Prediction_2025.csv")